spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://dpg-ct4vlj3qf0us73844750-a.oregon-postgres.render.com:5432/liquibase_i99u
    driver-class-name: org.postgresql.Driver
    username: charan
    password: eChfqpQtXfWSlxW8YMfg6TRG3Asck30v
  liquibase:
    change-log: classpath:db/changelog/master.xml
