spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://dpg-ct4u7shopnds73d4dkk0-a.oregon-postgres.render.com:5432/liquibase_i99u
    driver-class-name: org.postgresql.Driver
    username: charan
    password: xiHWSYuwuBf6BA8PJNUtb76GH7CZJAGU
  liquibase:
    change-log: classpath:db/changelog/master.xml
