spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: liquibase-learning
    password: Charan2002@
  liquibase:
    change-log: classpath:db/changelog/master.xml
  h2:
    console:
      enabled: true
